@startuml
start

:Запуск системы;

:Начало логирования данных;

if (Оси подключены?) then (нет)
    :Данные поступают в логи;
    :Графики не отображаются;
else (да)
    :Привязка каналов к осям графика;
    :Начало построения графиков;
endif

:Поступление телеметрии (непрерывно);

if (Запуск прогона?) then (да)
    :Изменение управляющих воздействий;
    :Изменение характера телеметрии;
else (нет)
endif

:Телеметрия продолжается независимо от прогона;

stop
@endumlне
