@startuml
start

:Запуск системы;
:Загрузка конфигурации подключения;

:Ожидание действий оператора;

:Настройка сценария испытаний;
:Валидация параметров сценария;

if (Конфигурация корректна?) then (да)
    :Фиксация конфигурации прогона;
else (нет)
    :Показать ошибку оператору;
    stop
endif

:Подключение к оборудованию;
:Проверка доступности осей;

if (Оборудование доступно?) then (да)
    :Разрешить запуск прогона;
else (нет)
    :Показать ошибку подключения;
    stop
endif

:Запуск прогона;

fork
    :Получение телеметрии;
    :Валидация телеметрии;
    :Логирование достоверных данных;
fork again
    :Формирование управляющих воздействий;
    :Передача команд на оси;
fork again
    :Построение графиков;
end fork

:Остановка прогона;

:Остановить получение телеметрии;
:Зафиксировать результаты;
:Сформировать отчёт;

stop
@enduml
