@startuml
left to right direction
actor "Оператор" as Operator

rectangle "Система испытаний" {

  (Настроить воздействие ветра) as UC_Wind

  (Задать формулу воздействия) as UC_Formula
  (Выбрать шаблон формулы) as UC_Template

  (Установить величину по шкале Бофорта) as UC_Beaufort
  (Установить направление ветра) as UC_Direction
  (Установить угол атаки) as UC_Angle

  (Выполнить расчёт испытания) as UC_Calc
  (Настроить протокол испытаний) as UC_Protocol
}

Operator --> UC_Wind

UC_Wind .> UC_Formula    : <<include>>
UC_Formula <. UC_Template : <<extend>>

UC_Wind .> UC_Beaufort   : <<include>>
UC_Wind .> UC_Direction  : <<include>>
UC_Wind .> UC_Angle      : <<include>>

Operator --> UC_Calc
Operator --> UC_Protocol
@enduml