@startuml
left to right direction
actor "Оператор" as Operator

rectangle "Система визуализации" {
  (Просматривать телеметрию в реальном времени) as UC_Tel
  (Просматривать графики управления) as UC_CtrlGraph
  (Настраивать отображение графиков) as UC_GraphSettings
  (Просматривать системные логи) as UC_Logs
}

Operator --> UC_Tel
Operator --> UC_CtrlGraph
UC_CtrlGraph <. UC_GraphSettings : <<extend>>
Operator --> UC_Logs
@enduml