@startuml
left to right direction

"Оператор" as o
"Система" as s

(Запускает испытания)                                  as UC1
o --> UC1

(Управляет данными телеметрии)                         as UC11
UC1 .> UC11 : <<include>>
(Устанавливает ось)                                    as UC111
UC11 .> UC111 : <<include>>
(Подключает к физическим осям)                         as UC1111
UC111 <. UC1111 : <<extend>>

(Строит график от формулы)                             as UC12
UC1 <. UC12 : <<extend>>
(Настраивает воздействие ветра)                        as UC121
UC12 <. UC121 : <<extend>>
(Устанавливает величину по шкале Бофорта)              as UC1211
UC121 <. UC1211 : <<extend>>
(Устанавливает направление ветра)                      as UC1212
UC121 <. UC1212 : <<extend>>
(Устанавливает формулу воздействия от времени)         as UC1213
UC121 <. UC1213 : <<extend>>
(Выбирает формулу из заготовленных шаблонов)           as UC12131
UC1213 <. UC12131 : <<extend>>
(Устанавливает угол атаки)                             as UC1214
UC121 <. UC1214 : <<extend>>


(Делает расчёт испытаний)                              as UC13
UC1 <.UC13 : <<extend>>
(Настраивает протокол испытаний)                       as UC131
UC13 <. UC131 : <<extend>>
(Выбирает тип испытания)                               as UC1311
UC131 <. UC1311 : <<extend>>
(Формирует отчёт)                                      as UC1312
UC131 <. UC1312 : <<extend>>
(Изменяет конфигурацию устройства)                     as UC1313
UC131 <. UC1313 : <<extend>>

(Просматривает логи системы)                           as UC2
o --> UC2

(Просматривает графики управления в реальном времени)  as UC3
i --> UC3
(Редактирует параметры графиков)                       as UC31
UC3 <. UC31 : <<extend>>
(Редактирует кривую)                                   as UC311
UC31 <. UC311 : <<extend>>
(Редактирует ось)                                      as UC312
UC31 <. UC312 : <<extend>>
(Редактирует параметры изображения)                    as UC313
UC31 <. UC313 : <<extend>>
(Настраивает подзаголовки)                             as UC32
UC3 <. UC32 : <<extend>>

(Контролирует график управления)                       as UC4
o --> UC4
(Устанавливает время теста)                            as UC41
UC4 <. UC41 : <<extend>>
(Выбирает тип теста)                                   as UC42
UC4 <. UC42 : <<extend>>
(Запускает/останавливает двигатели)                    as UC43
UC4 <. UC43 : <<extend>>

(Контролирует график телеметрии)                       as UC5
o --> UC5
(Устанавливает шаг графика в секундах)                 as UC51
UC5 <. UC51 : <<extend>>
(Выбирает ось)                                         as UC52
UC5 <. UC52 : <<extend>>
(Удаляет ось)                                          as UC521
UC52 <. UC521 : <<extend>>

(Создаёт вывод готовности воздушного средства к эксплуатации на основе параметров конфигурации) as UCs1
(Генерирует комментарий конфигурации)                                                           as UCs2
(Генерирует отчёт)                                                                              as UCs3

s --> UCs1
s --> UCs2
s --> UCs3

note right of UC111
  По умолчанию используется подключение к виртуальным осям
end note

note right of UCs2
  Генерируется автоматически, исходя из конфигурации устройства для упрощения воспиятия параметров испытания
end note

@enduml